export const FETCH_DECKS = 'FETCH_DECKS'
export const RECEIVE_DECKS = 'RECEIVE_DECKS'
export const FETCH_DECK = 'FETCH_DECK'
export const SAVE_DECK = 'SAVE_DECK'
export const DELETE_DECK = 'DELETE_DECK'
export const ADD_CARD = 'ADD_CARD'